### ISSUE TITLE
Facebook doesn't work anymore ?

### ISSUE THREAD

**Issue by sorgniard** [pavelk2/social-feed#100]
Hey !
I used your script some weeks ago, and now, i don't get post from Facebook anymore !
Is it normal ? 
There is not any facebook posts in your demo too !

**Comment by pavelk2** [comment]
Thank you very much for pointing this out. I created a fix, please check out the commit connected to this issue.

**Comment by sorgniard** [comment]
Thank you, it works

By the way the getUserId function in your utility facebook doesn’t works anymore, because it needs the access token now !

Pierre Guihéneuf

CabinetSorgniard

Interactive marketing & business management

7, rue George Sand. 37 000 Tours

Tél. 02 47 60 90 69

www.sorgniard.com http://www.sorgniard.com 

De : Pavel Kucherbaev [mailto:notifications@github.com] 
Envoyé : mercredi 24 juin 2015 15:51
À : pavelk2/social-feed
Cc : sorgniard
Objet : Re: [social-feed] Facebook doesn't work anymore ? (#100)

Thank you very much for pointing this out. I created a fix, please check out the commit connected to this issue.

**Comment by pavelk2** [comment]
But I think that it is exactly what I fixed:
https://github.com/pavelk2/social-feed/blob/gh-pages/js/jquery.socialfeed.js#L308
I added an access_token there.

**Comment by sorgniard** [comment]
Oh my bad, strange i must have done bad things ;)

Thank you

Pierre Guihéneuf

CabinetSorgniard

Interactive marketing & business management

7, rue George Sand. 37 000 Tours

Tél. 02 47 60 90 69

www.sorgniard.com http://www.sorgniard.com 

De : Pavel Kucherbaev [mailto:notifications@github.com] 
Envoyé : mercredi 24 juin 2015 16:46
À : pavelk2/social-feed
Cc : sorgniard
Objet : Re: [social-feed] Facebook doesn't work anymore ? (#100)

But I think that it is exactly what I fixed:
https://github.com/pavelk2/social-feed/blob/gh-pages/js/jquery.socialfeed.js#L308
I added an access_token there.

**Comment by pavelk2** [comment]
No problem. Let me know if there are any more issues.
