### ISSUE TITLE
Multi-columns

### ISSUE THREAD

**Issue by freewalkzurich** [pavelk2/social-feed#105]
Hello,

social-feed looks beautiful on a single column, and there's no simple way to put it on multiple columns. With  the column-count property, the columns are not aligned at the top. Any ideas? Would be great to have this feature.

Kind regards,
Julien

**Comment by digitalesherz** [comment]
first I'd like to see it working for me! do you have tips on getting it working?

**Comment by freewalkzurich** [comment]
Hello,

At the moment I am using a bit of simple CSS:
               .social-feed-container {
    -webkit-column-count: 3; /\* Chrome, Safari, Opera _/
    -moz-column-count: 3; /_ Firefox */
    column-count: 3;
}

See it live at the end of this page: http://freewalkzurich.ch/

but this produces misalignements at the top.

This seems to be that, where there is space at the top, it is some post
which is not displayed but for which space is reserved. Any ideas?

Kind regards,
Julien

On Tue, Jul 7, 2015 at 4:37 PM, digitalesherz notifications@github.com
wrote:

> first I'd like to see it working for me! do you have tips on getting it
> working?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pavelk2/social-feed/issues/105#issuecomment-119223864
> .

## 

_info@freewalkzurich.ch info@freewalkzurich.ch_
_0041 77 405 89 66_

**Comment by matthewjrallen** [comment]
I use Masonry to do this

http://masonry.desandro.com/

**Comment by freewalkzurich** [comment]
Hi Matthew,

That looks good! Would you maybe have an example of what needs to be
changed in social-feed to integrate it?

Best,
Julien

On Wed, Jul 15, 2015 at 10:05 AM, Matthew Allen notifications@github.com
wrote:

> I use Masonry for to do this
> 
> http://masonry.desandro.com/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pavelk2/social-feed/issues/105#issuecomment-121523323
> .

## 

_info@freewalkzurich.ch info@freewalkzurich.ch_
_0041 77 405 89 66_

**Comment by matthewjrallen** [comment]
Nothing really need to be changed to social-feed. The only issue i'm having at the moment is I have to delay the masonry call to make sure that it starts after social-ffed loads as masonry won't work properly. I use a timeout function delay it. 

```
setTimeout(function() {
 $('.social-feed-container').masonry({
// options
itemSelector: '.social-feed-element'
  });
}, 3000)
```

**Comment by freewalkzurich** [comment]
Cool, I managed: (scroll down http://www.freewalkzurich.ch/ )

@pavelk2:

the code is

<style>
.social-feed-element {width: 32%; margin-left: 10px; margin-top: 0px;
margin-bottom: 10px;}
.social-feed-container {width: 100%;}
</style>

after loading jquery:

<script src="
https://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.1/masonry.pkgd.min.js
"></script>

in $(document).ready, after updateFeed()

setTimeout(function() {
 $('.social-feed-container').masonry({
// options
 itemSelector: '.social-feed-element'
  });
}, 3000);

Best,
Julien

On Fri, Jul 17, 2015 at 10:17 PM, Matthew Allen notifications@github.com
wrote:

> Nothing really need to be changed to social-feed. The only issue i'm
> having at the moment is I have to delay the masonry call to make sure that
> it starts after social-ffed loads as masonry won't work properly. I use a
> timeout function delay it.
> 
> setTimeout(function() {
>  $('.social-feed-container').masonry({
> // options
> itemSelector: '.social-feed-element'
>   });
> }, 3000)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pavelk2/social-feed/issues/105#issuecomment-122401145
> .

## 

_info@freewalkzurich.ch info@freewalkzurich.ch_
_0041 77 405 89 66_

**Comment by pavelk2** [comment]
Great,

Please pay attention, that on 1920px your feed looks like this:
https://www.dropbox.com/s/vmfylwr5ombsmij/Screenshot%202015-07-20%2014.10.09.png?dl=0
While on 1440px (MacBook 13") it is cut:
https://www.dropbox.com/s/yyb325g7yqvvhuk/Screenshot%202015-07-20%2014.11.01.png?dl=0

**Comment by pavelk2** [comment]
fix the width for the container

**Comment by Webarkitekt** [comment]
@freewalkzurich @matthewjrallen 
Why do you guys don't use the callback to load masonry after feeds load ?

**Comment by ShapesGraphicStudio** [comment]
Hi @matthewjrallen,
Thanks for the timeout trick.
Only problem is that it's not the most beautiful when the page loads..
Maybe we should add a loader function to hide it all first.. ?
