### ISSUE TITLE
Facebook account settings ! mark

### ISSUE THREAD

**Issue by njtam** [pavelk2/social-feed#106]
Hi Pavel,

I'm going through the Facebook account settings and reading previous issues on the forum.  I understand that the @username option does not work and #hashtag API is deprecated by Facebook. So I guess the only option is to use the !searchword option?  

I am confused as to how the ! mark pulls data.  Does it look for public posts containing the string after the ! mark?

Just looking for the best way to use the ! mark to target posts. :)

Thanks in advance,
NJ

**Comment by pavelk2** [comment]
Hi @njtam 
Try to use facebook_page_id, I believe this should work well.
https://github.com/pavelk2/social-feed/blob/gh-pages/js/jquery.socialfeed.js#L316
