### ISSUE TITLE
Geotagged feed?

### ISSUE THREAD

**Issue by md409** [pavelk2/social-feed#110]
How would you change the code to incorporate hashtags as well as geotagged media? ie I want all #stanford photos + anything within a 3 mile radius of 37.43, 122.17.

**Comment by Webarkitekt** [comment]
@md409 @pavelk2 This looks perhaps a bit too specific, plus not every api have the ability to send geographic coords of the user.

**Comment by pavelk2** [comment]
@Webarkitekt 
If we focus specifically on @md409 request, not thinking how this should be implemented in a general version of social-feed, then I would say that we need (based on Instagram as a network supporting location tagging):

search for a specific location: 

```
 https://api.instagram.com/v1/locations/search?distance=3000&lat=37.43&lng=122.17&access_token=ACCESS-TOKEN
```

search for posts in a given location:

```
https://api.instagram.com/v1/locations/{location-id}/media/recent?access_token=ACCESS-TOKEN
```

Then we need to filter out only posts having hash-tags we care about. Check how to filter out response based on hashtags here: http://instagram.com/developer/endpoints/tags/.

Other social-networks could follow similar steps.

**Comment by pavelk2** [comment]
I believe that the answer is given. It is not really supported by the plugin in a general way.
