### ISSUE TITLE
any help to implement the code please 

### ISSUE THREAD

**Issue by kamilon50** [pavelk2/social-feed#119]
I have implemented your social feed to http://plugmedia.kamil-kus.ie/ but I don't know why is not workinmg any assistance would nicely welcomed.

Kind Regards,

Kamil

**Comment by joshf** [comment]
+1 on this, its something with facebook graph not getting the account id properly i think

**Comment by kamilon50** [comment]
I will try tomorrow to create facebook app directly from plugmedia account.

Thank for the advice, let me know if you would have any other suggestions please

Regards
Kamil

**Comment by kamilon50** [comment]
I think all the structure is fine css and js links + div skeleton

**Comment by etienne-martin** [comment]
https://github.com/pavelk2/social-feed/issues/116

**Comment by Webarkitekt** [comment]
@kamilon50 did you get it to work ?

**Comment by kamilon50** [comment]
No I didn't I have found something else as swocialfeed took to much time to
integrate + was all the time something wrong with it.

But big thanks for a support, maybe next time will work.

All the Best,

Kamil

All the Best,

Kamil
| CKdesign
http://t.sidekickopen30.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XX43MPfv6Vd0yGC7fK95-VRJgRK56dPKmf6tNWk202?t=http%3A%2F%2Fckdesign.eu%2F&si=4632408293113856&pi=0724ef78-4bd0-4a61-994c-4f23700f1291
