### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by oresh** [pavelk2/social-feed#12]
Clean js, css (unnecessary repeats), reduce icon sizes

**Comment by oresh** [comment]
https://raw.github.com/oresh/social-feed/master/css_js_clean_up.patch
first attampt

**Comment by pavelk2** [comment]
I have applied the given patch. Some errors are fixed. the size of the pictures is still the same. Patch did not affect the size of the pictures, so i guess we need to update them manually.

**Comment by oresh** [comment]
Sorry, didnt test properly.
Some fixes. (includes your fixes too)
https://raw.github.com/oresh/social-feed/master/css_js_clean_up-1.patch

**Comment by pavelk2** [comment]
fixed
