### ISSUE TITLE
twitter still requests token when consumer_key/secret not set

### ISSUE THREAD

**Issue by joshuaatkins** [pavelk2/social-feed#120]
It has been observed on some installations of this plugin that where are set to empty, the plugin still attempts to open a connection and retrieve a token from twitter. This then appears to loop every second applying alot of load to the codebird-js api. 

consumer_key: '', 
consumer_secret: ''

A check should be added, that if a key or secret is not provided no initialisation of the script is attempted.

**Comment by Webarkitekt** [comment]
Why do you need to keep twitter configuration parameters ? If you don't need to show twitter posts, just remove the twitter configuration.
