### ISSUE TITLE
Order

### ISSUE THREAD

**Issue by medinlu** [pavelk2/social-feed#122]
How social-feed is ordering the posts? Latest by date?

I have facebook, twitter and instagram feeds from the same users. So... If a user posts the same content on the different networks, how can I randomize the order to get something more dynamic and the same repeated content?

Have an example: (first one is twitter, second is twitter)

![captura de pantalla 2015-09-21 a la s 14 09 24](https://cloud.githubusercontent.com/assets/832597/9991447/62821b8a-606a-11e5-82c5-d98e54dac4fd.png)

**Comment by asiriyo-kor** [comment]
jquery.socialfeed.js 129line
if ($(this).attr('dt-create') < data.dt_create) {
......

Latest by date

**Comment by Webarkitekt** [comment]
@asiriyo-kor thanks for the answer ;)
