### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by nickredmark** [pavelk2/social-feed#124]
By using this with facebook you have to expose your app secret on the client, which results in the following issues:

http://stackoverflow.com/questions/16532261/what-could-someone-do-if-they-got-hold-of-my-facebook-app-id-secret

**Comment by Webarkitekt** [comment]
It rely on your app permissions. But anyway, a js node extension of this plugin is in development to provide Access token via server side. https://github.com/pavelk2/social-feed-server
