### ISSUE TITLE
HELP WITH THE CODE ??

### ISSUE THREAD

**Issue by kamilon50** [pavelk2/social-feed#138]
Hello Everyone

I'm trying to implement that code i think countless times and I'm not sure what am I doing wrong any assistance please.

Kamil

**Comment by Webarkitekt** [comment]
Have you any preview ?

**Comment by kamilon50** [comment]
http://kamil-kus.ie/plugmedia2/

**Comment by kamilon50** [comment]
its on the home page under services section

**Comment by Webarkitekt** [comment]
Check your browser console you have some error, including a 404 on "js/jquery.socialfeed.js"

**Comment by kamilon50** [comment]
thanks is done but i still getting 
"Uncaught ReferenceError: jQuery is not defined
kamil-kus.ie/:279 Uncaught ReferenceError: $ is not defined "

**Comment by Webarkitekt** [comment]
It's better to Load jQuery lib before social feed plugin :dancers:
