### ISSUE TITLE
Google feed API deprecated

### ISSUE THREAD

**Issue by HartLarsson** [pavelk2/social-feed#147]
Google seems have removed the feed API and not wht rss part of the script not work anymore.
There are alternatived?

**Comment by kamaleao** [comment]
http://blog.superfeedr.com/google-feed-api-alternative/

**Comment by Webarkitekt** [comment]
Fixed, it works nicely with YQL api. Thanks guys. Let me know if it works for you.

**Comment by HartLarsson** [comment]
YQL service by Yahoo is down since hours, i've a tremendous feeling that they will move to a pay service. Could be great to implement another service or a hosted php rss2json function.
I found another service but the json result is not complete to be used instead of YQL
http://rss2json.com/
