### ISSUE TITLE
Twitter API 1.1

### ISSUE THREAD

**Issue by joemaffia** [pavelk2/social-feed#15]
Are u planning to migrate to the new Twitter API 1.1? 'cause the 1.0 will be deprecated by end of this month :(

Cheers

**Comment by pavelk2** [comment]
Yes i do plan. I don't know yet the structure of the new API, but i guess that i will take care about it on the next 2 weeks.

**Comment by joemaffia** [comment]
no much of change... if not that any endpoint require authentication now :(

**Comment by marvellimited** [comment]
Hello, have you manage to migrate to the new Twitter API 1.1?? 
Thanks

**Comment by pavelk2** [comment]
Hello, now you can not get data from Twitter, using only javascript - you have to get data on the server side and then extract it via javascript. I have it implemented, but i will put it on github - only in one month or about that. Go to gitbox.ru/social-feed-1.1 - in one week - i will publish a new version there.

**Comment by marvellimited** [comment]
Oh okay, i hear that...
The link you gave me is invalid, but i will check back on here in a week.

Thanks very much
keep up the good work!!

**Comment by marvellimited** [comment]
Hello, How is it going?
have you managed to get the new API working??

Thanks

**Comment by notslang** [comment]
I made a plugin for getting twitter posts on the client-side with just JS that you could use for this: https://github.com/slang800/twitterFetcher

**Comment by pavelk2** [comment]
Great, appreciate! I will give it a look and will prepare integration as soon as i have some free time slot.

**Comment by sigurdsn** [comment]
I'm also missing twitter in my feed, would love to have this feature re-enabled.

**Comment by pavelk2** [comment]
i will try to re-implement it soon

**Comment by notslang** [comment]
@pavelk2: cool! HMU if you need any help using twitterFetcher

**Comment by sigurdsn** [comment]
Hey. I've found [tweecool](https://github.com/tweecool/tweecool-jquery-plugin) which has an API (probably with its own v1.1 authentication) to provide a JSON feed of a twitter users feed. Again this does not support filter for tags, nor handy information like the ID of each post - BUT it gives a authentication-free JSON feed for Twitter.
So I've re-implemented twitter to socialfeed in my own way, using some code I've found from an earlier commit and the URL from tweecool (ex. http://api.tweecool.com/?screenname=google&count=5). To replicate, make sure you re-add twitter to the 'options'-list of social network, then add this block as sibling to the other social network sections of the code:

``` javascript
twitter : function(account) {
    var request_url, limit = '&count=' + options.twitter.limit;

    switch (account[0]){
        case '@':
        var username = account.substr(1);
        request_url = 'http://api.tweecool.com/?screenname=' + username + limit;
        get_request(request_url,getPosts);
        break;
        case '#':
        break;
        default:
        request_url = 'http://api.tweecool.com/?screenname=' + username + limit;
        get_request(request_url,getPosts);
    }

    function getPosts(json) {
        var urlpattern = /(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig;
        var i = 0;

        $.each(json.tweets, function() {
            var element = this, post = {};
            i ++;

            post.id = json.user.id + '-' + i; // Feed doesn't provide post ID
            post.dt_create = moment(element.created_at);
            post.author_link = 'http://twitter.com/'+username;
            post.author_picture = json.user.profile_image_url;
            post.post_url = post.author_link; // + '/status/' + element.id_str; Feed doesn't provide post ID
            post.author_name = username;
            post.message = element.text.replace(urlpattern, '<a href="$1" target="_blank">$1</a>');
            post.description = '';
            post.social_network = 'twitter';
            post.link = 'http://twitter.com/' + post.author_name; // + '/status/' + element.id_str; Feed doesn't provide post ID

            getTemplate(post,json.tweets[json.tweets.length-1] == element);
        });

    }

},
```

Also remember to add twitter settings to your "index"-file or wherever you initiate the script. At least this is one way of having Twitter back in the social-feed script... Enjoy!

**Comment by pavelk2** [comment]
@sigurdsn, thank you very much for your solution
As the tweecool is quite limited (no images, no search by hash-tags), I kept searching for alternatives and finally found https://github.com/jublonet/codebird-js. Thanks to this library, now we have twitter supported back at SocialFeed.

Please check the latest update
https://github.com/pavelk2/social-feed/commit/885a7db6ab286a504dad62a14f1e2b8846e6cead

**Comment by sigurdsn** [comment]
Hey! That looks awesome - congrats on re-implementing it to SocialFeed.
