### ISSUE TITLE
Instagram: search tags only in my account ?

### ISSUE THREAD

**Issue by ghost** [pavelk2/social-feed#192]
Hello guys, for Instagram...search: #bellariaigeamarina, this research found only post my account . (Which is precisely called bellariaigeamarina)
Possible ?
There's ways to do a global search? in all account whit this #bellariaigeamarina (but has to be a hashtag )
the call is this:
https://api.instagram.com/v1/tags/bellariaigeamarina/media/recent/?access_token=MY-TOKEN&count=2&callback=?
I think it is correct.

Thank you so much

**Comment by HartLarsson** [comment]
you can play with https://apigee.com/console/instagram
and check yourself that searching hashtags by api are limited only by your account.

**Comment by ghost** [comment]
Perfect! Thanks a lot for the answer.
