### ISSUE TITLE
RSS feed support 

### ISSUE THREAD

**Issue by MaluNoPeleke** [pavelk2/social-feed#193]
Is it possible to add a RSS feed support as an "account"?

**Comment by HartLarsson** [comment]
RSS is already supported, what you mean with "as an account"?

```
    rss:{
        urls: ['http://teslapodcast.libsyn.com/rss'], //Array: Specifiy a list of rss feed from which to pull posts
        limit: 2                                      //Integer: max number of posts to load for each url
    }
```

RSS feed are based o public URLs.
If you want a better RSS implementation (not only Text) i've added in my fork a more complex RSS part. Feel free to take a look. I actually use to grab RSS feed from blogspot, wordperss and other feeds with text and Images.

**Comment by MaluNoPeleke** [comment]
Thanks, I haven't seen that. Sorry for the opened issue.
