### ISSUE TITLE
Question: what is the states on the BlogPost feed option?

### ISSUE THREAD

**Issue by weilinzung** [pavelk2/social-feed#203]
Hi,

Just want to ask if still possible to show the feed from BlogPost (like Wordpress)? 

THANKS!

**Comment by HartLarsson** [comment]
using RSS option you can read any rss blog feed.
If you are interested on display also pic in the feed and not only text please check my forked version

**Comment by weilinzung** [comment]
thanks, but what is the forked version? link?

**Comment by HartLarsson** [comment]
you can reach every forked version browsing people profiles (mine in my case) https://github.com/HartLarsson/social-feed
