### ISSUE TITLE
Twitter Invalidate Date on IE

### ISSUE THREAD

**Issue by Kimutua** [pavelk2/social-feed#207]
Assist debug a fore mentioned, this only happens on internet explorer.
![invalid date](https://cloud.githubusercontent.com/assets/12655740/18515672/c852ec06-7a9e-11e6-98a5-8976dd54e11a.PNG)

**Comment by stillatmylinux** [comment]
Refer to this pull request https://github.com/pavelk2/social-feed/pull/204

**Comment by HartLarsson** [comment]
i've fixed it changing the line 272 from

`post.dt_create = moment(new Date(element.created_at));`

to

`post.dt_create = moment(element.created_at, 'dd MMM DD HH:mm:ss ZZ YYYY');`

**Comment by johnzilojo** [comment]
@HartLarsson Thanks soo much for the solution. It works great.

**Comment by Kimutua** [comment]
Thanks guys, works perfectly.

**Comment by martijngastkemper** [comment]
Solved by merging #212
