### ISSUE TITLE
Twitter won't work

### ISSUE THREAD

**Issue by makz3l** [pavelk2/social-feed#209]
I followed all the steps on the installation guide and I still couldn't get twitter to work. Here's my Website: [Makzel](http://makzel.com/makzel)

**Comment by HartLarsson** [comment]
please use google chrome F12 debug option and check your console!

**Comment by HartLarsson** [comment]
plus check your scripts for errors like:

![image](https://cloud.githubusercontent.com/assets/16102074/18584123/21b36eda-7c0f-11e6-876c-4b3012f9dc34.png)

**Comment by makz3l** [comment]
I'm getting an error that says template.html not found

**Comment by HartLarsson** [comment]
the plugin not find the template.html file in this location

http://makzel.com/test2/template.html

you need to move template.html in the right place or specify another template.html place in a diff subfolder using the explained parameter in the javascript initialization part (see the home page of the GitHUB and scroll down)

**Comment by makz3l** [comment]
It is working now. I've set the limit to 2 but it's only showing one of my tweets. Also, instagram isn't working. :(

**Comment by makz3l** [comment]
It works now. But the limit option isn't working. I have it set to 2 but it's only showing one.

**Comment by HartLarsson** [comment]
same code syntax error!
https://github.com/pavelk2/social-feed/issues/211

**Comment by martijngastkemper** [comment]
I'll close this issue, because it's solved. The limit problem will continue in #211
