### ISSUE TITLE
Facebook feeds are not being pulled

### ISSUE THREAD

**Issue by ktharmabalan** [pavelk2/social-feed#210]
Facebook feeds are not being pull anymore. It was working before but suddenly stopped working. Twitter feeds are being pulled without an issue though.

**Comment by eirikkw** [comment]
I had the same issue earlier today. The fix for me was to create a new Facebook app. Apparently the old one had reached it's request limit: https://developers.facebook.com/docs/marketing-api/api-rate-limiting

**Comment by ktharmabalan** [comment]
That fixed it. Thank you.
