### ISSUE TITLE
Instagram Issues

### ISSUE THREAD

**Issue by TestCandidate** [pavelk2/social-feed#220]
I see that there are other submitted issues regarding Instagram not working, without a reasonable mentioned solution. 

Can anyone update us regarding this matter? 

I am getting the error:
jquery.socialfeed.js:516 Uncaught TypeError: Cannot read property 'id' of undefined

I am using my own ClientId, returns an error even against my own account.

my app is in sandbox mode - i want to access my own account so this should be fine.

any advise? 

*\* Update *\* 
Adding An Access Token Seem To Work, 
But what is the consequences of having the access token in the client side, any security issues that I should be worried about ?

**Comment by HartLarsson** [comment]
i still using instagram too without any problem. 

as explained in the xample here:

```
        client_id: 'YOUR_INSTAGRAM_CLIENT_ID',       //String: Instagram client id (option if using access token)
        access_token: 'YOUR_INSTAGRAM_ACCESS_TOKEN' //String: Instagram access token

```

client_id is optional but not access_token!
The main problem about ID and tokens in public is a question we have discussed time ago and Pavel tried to provide a solution using social-feed server idea.

https://github.com/pavelk2/social-feed-server

**Comment by TestCandidate** [comment]
I checked the repo. This seems to rely on angular which I am not including in my project for this level. 

As for the security risks, my question is, how bad is this implementation? What are the risks that i should be considering ? 

Do you have a link for the discussion details please?

**Comment by HartLarsson** [comment]
one discussion was here https://github.com/pavelk2/social-feed/issues/44

**Comment by TestCandidate** [comment]
To Sum Up, this plugin is awesome, yet its usage is not recommended. makes everyone using it vulnerable.

Thank you for your help.
