### ISSUE TITLE
Facebook Issue

### ISSUE THREAD

**Issue by retox001** [pavelk2/social-feed#23]
Hi Pavel,

Firstly i really like the social feed tool and think it is very useful.

I have tested it on my local machine and it works fine with the Obama example but when i add my own username and token it doesn't work.

Can there be a cache issue? or is there a time delay when a new token is created?

I know the user name and token is correct as when i manually enter the URL the feed gets displayed, if you could please let me know what is causing the issue i would be most grateful.

p.s. here is the URL link of the FB feed to prove the token is correct

https://graph.facebook.com/therakuman/feed?&access_token=240696342763428|FgHgjfn7wWMNT15ONHP0tVdWm_k

/// Update ///

I have now released what the issue was and that instead of putting my username i had to put my first name then a dot and then my last name to pull out the feed.

Can i ask why it will not work with my username??

My username feed is pulling in the correct info where as my name does not but simply show 2 post is it something to do with my Facebook settings? if so can you please advice

**Comment by pavelk2** [comment]
Hi,

In fact if you put your first.last name then you will get another guy https://www.facebook.com/eddie.kent.
The actual reason is with the "limit" parameter. Up to now - i do not know exactly why does it work with my username, barackobama and etc, but do not work with yours. I found that if to take out the &limit=2 parameter - then it works fine. 
I need to investigate. If you will find the solution sooner -please let me know.

**Comment by retox001** [comment]
Hi Pavel,

Thanks for the quick response, I think it was a number of reasons why it wasn't working for me it is working fine now as the feed is being pulled in correctly.

I required the content from a FB page and have used the FB page Name as the username and it works fine for me apart from the FB_limit variable.

If i set the limit to 2 - it shows 2, if i set it to 3 - it show 2  and if i set it to 4 - it shows 3

Is this a known issue? or is it depended on what the content is from Facebook? e.g if it is a event or gallery it will not count it or skip it?

Thanks again in advance

**Comment by pavelk2** [comment]
There is some internal Facebook logic - which retrieves posts according to smth. For example - if the latest post was posted 6 months ago, then the API endpoint will not retrieve anything. In SocialFeed - there is no any additional logic - just take whatever facebook gives. So to be honest - I can not give any detailed explanation to this issue.
Just - want to make a point, that I have just fixed some bug about GooglePlus and also added a support for Instagram.

**Comment by retox001** [comment]
Thanks Pavel,

I know before the Twitter API change i experienced a similar issue with the feed generated from my twitter account where it wouldn't count certain tweets due to some logic but i was not using your Social Feed.

Thanks again for your quick response on this issue it is very much appreciated and i will now close the issue.
