### ISSUE TITLE
Is it possible to retreive the amount of likes and comments?

### ISSUE THREAD

**Issue by mikavs** [pavelk2/social-feed#239]
Is it possible to retreive the amount of likes and comments for Facebook?

**Comment by HartLarsson** [comment]
is possible reconfiguring the facebook graph api call, but need a reimplementation of all the facebook part plus a new template to hold the new infos.
if you have time to implement and want to contribute here you can read some example:

http://stackoverflow.com/questions/17755753/how-to-get-likes-count-when-searching-facebook-graph-api-with-search-xxx
