### ISSUE TITLE
RSS feed is not working

### ISSUE THREAD

**Issue by loryzz** [pavelk2/social-feed#243]
The Google Feed API, used by social-feed, is officially deprecated and it doesn't work from December 16th, 2016: https://developers.google.com/feed/v1/reference
I think it needs to be replaced with a new RSS API.

**Comment by HartLarsson** [comment]
I still using the latest version with any problem for RSS feed.
The google feed api solution was removed many month ago from the js.
We still use https://query.yahooapis.com/v1/ solution instead and its working perfectly right now,
Please update to latest version of social-feed

**Comment by loryzz** [comment]
Ok, I think I was using the latest official release (0.1.2). Updating to the latest version fixes the issue.
