### ISSUE TITLE
Facebook image issue

### ISSUE THREAD

**Issue by ecbbce** [pavelk2/social-feed#267]
I retrieved the facebook posts of a company page, however since a couple of days the image will not load.

In the HTML on the website the following source of the image is set of one of the posts https://graph.facebook.com/892444634257084/picture/?type=normal

but the output is:
{
   "error": {
      "message": "Unsupported get request. Object with ID '892444634257084' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api",
      "type": "GraphMethodException",
      "code": 100,
      "fbtrace_id": "GgJU/qKwsS4"
   }
}

I found something about the 100 error, maybe facebook changed their policy? https://stackoverflow.com/a/20959339

Any suggestions? Thank you.

**Comment by Hypocrite** [comment]
Same problem here.

**Comment by HartLarsson** [comment]
can you provide a page or a jsfiddle to debug the problem?

**Comment by HartLarsson** [comment]
seems to me a visibility poblem of the page you try to grab. Is published? the app you create for socual-feed is allowed by the page?

**Comment by ecbbce** [comment]
Maybe I have to check the rights of the company facebook page, however it is weird that the text of the post is visible but only the image is broken. At this Dutch website you see the facebook widget on the bottom of the screen. www.stadhardenberg.nl (screenshot). Some are broken. I can create a jsfiddle later on.
![image](https://user-images.githubusercontent.com/2444655/27580148-0f4fd2c4-5b2a-11e7-9883-ab95a8538826.png)

**Comment by Hypocrite** [comment]
It can grap the text content but images are broken. I tried to check the Facebook page permissions but did not find anything related. Access token should be ok because the post content is coming through except the images. I can try creating a Plunker from it later.

Looking at Network tab, it tries to get https://graph.facebook.com/10155558446906392/picture/?type=normal which results in 400 with error with response:
```{
   "error": {
      "message": "Unsupported get request. Object with ID '10155558446906392' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api",
      "type": "GraphMethodException",
      "code": 100,
      "fbtrace_id": "B3FRbK/ajTN"
   }
}```

**Comment by Hypocrite** [comment]
Seems like the problem fixed itself. Images are loading again.

**Comment by ecbbce** [comment]
Yes probably something at facebook... I will close the issue for now.
