### ISSUE TITLE
add since and until filters in the query of feeds

### ISSUE THREAD

**Issue by geomichalis** [pavelk2/social-feed#28]
if your filter is only the number of feeds, there can be case that you "lose" to display some feeds.
the correct way is to filter from a specific time to another (preserving the limit of feeds)

i am working on this and i ll submit any result.

**Comment by pavelk2** [comment]
Appreciate!

**Comment by pavelk2** [comment]
Duplicate with https://github.com/pavelk2/social-feed/issues/28

**Comment by pavelk2** [comment]
Duplicate with https://github.com/pavelk2/social-feed/issues/26
