### ISSUE TITLE
Facebook feed doesn't work

### ISSUE THREAD

**Issue by vushe** [pavelk2/social-feed#290]
I'm using plugin for first day, so maybe missing something. But Facebook feed has disappeared a few minutes ago?

**Comment by vushe** [comment]
Works again. Will test more with personal token and reopen issue by the need

**Comment by vushe** [comment]
I don't definitely understand what's going on. Issue repeated again with my personal token. Looks like Facebook feed is unstable. Nothing is displayed on page load in browser. Console is clean too.

**Comment by shinoo187** [comment]
Me too : Nothing is displayed on page load in browser. Console is clean too.

**Comment by vushe** [comment]
It actually works fine. Issue seem to be related to app token. So you need to obtain one from [Facebook](https://developers.facebook.com/tools-and-support/).

Please note that provision of your token in public code can be somewhat insecure.

**Comment by shinoo187** [comment]
Hello,

yet even when I take your test model (with the test token) it does not 
work.

I have as error in the console:

XML parsing error: tag not matching. Expected: </ img>
Location: /bower_components/social-feed/template.html
Line number 1, Column 275:

for it to work I use another template:

template_html:
                 '<div class="social-feed-element {{? 
!it.moderation_passed}}hidden{{?}}" dt-create="{{=it.dt_create}}" 
social-feed-id = "{{=it.id}}"> \
     <div class="content"> \
         <a class="pull-left" href="{{=it.author_link}}" target="_blank"> \
             <img class="media-object" src="{{=it.author_picture}}"> \
         </a> \
         <div class="media-body"> \
             <p> \
                 <i class="fa fa-{{=it.social_network}}"></i> \
                 <span class="author-title">{{=it.author_name}}</span> \
                 <span class="muted pull-right"> {{=it.time_ago}}</span> \
             </p> \
             <div class="text-wrapper"> \
                 <p class="social-feed-text">{{=it.text}} <a 
href="{{=it.link}}" target="_blank" class="read-button">read more</a></p> \
             </div> \
         </div> \
     </div> \
     {{=it.attachment}} \
</div>',

But it works for twitter but not facebook

Do you have an idea ?

Dimitry


Le 25/11/2017 à 20:13, Valentin Dzhankhotov a écrit :

**Comment by shinoo187** [comment]
Hello,

yet even when I take your test model (with the test token) it does not work.

I have as error in the console:

`XML parsing error: tag not matching. Expected: </ img>
Location: /bower_components/social-feed/template.html
Line number 1, Column 275:`

for it to work I use another template:

`template_html:
                '<div class="social-feed-element {{? !it.moderation_passed}}hidden{{?}}" dt-create="{{=it.dt_create}}" social-feed-id = "{{=it.id}}"> \
    <div class="content"> \
        <a class="pull-left" href="{{=it.author_link}}" target="_blank"> \
            <img class="media-object" src="{{=it.author_picture}}"> \
        </a> \
        <div class="media-body"> \
            <p> \
                <i class="fa fa-{{=it.social_network}}"></i> \
                <span class="author-title">{{=it.author_name}}</span> \
                <span class="muted pull-right"> {{=it.time_ago}}</span> \
            </p> \
            <div class="text-wrapper"> \
                <p class="social-feed-text">{{=it.text}} <a href="{{=it.link}}" target="_blank" class="read-button">read more</a></p> \
            </div> \
        </div> \
    </div> \
    {{=it.attachment}} \
</div>',
`

But it works for twitter but not facebook

Do you have an idea ?

Dimitry

**Comment by vushe** [comment]
Hi!
Test token seem to be expired or such.

**Comment by vushe** [comment]
Cannot tell what's wrong with the template. I confirm that I have no issues like that and Facebook feed is fine with my custom token.

**Comment by shinoo187** [comment]
When I created my facebook app me API version is v2.11 and i have for the moment left the app in development mode for testing. Is this the way to go?

**Comment by shinoo187** [comment]
It's Work ! 
the problem of template came from a problem of cross-domain ... (and the other piece of code which replaced the template.html managed only the tweets) Thank you!

**Comment by vushe** [comment]
Glad it's working. Thanks for letting us know and good wishes! :)
