### ISSUE TITLE
Twitter taking a long time to load tweets

### ISSUE THREAD

**Issue by bluelevel-media** [pavelk2/social-feed#302]
Is anyone else having this issue? I have this feed running on a few sites and all of them which use twitter are taking a long time to load (about 10 seconds). This is affecting the styling of some sites. 

This seems to be consistent on all my sites but doesn't seem to have been raised by anyone else yet. It has been happening for about a week now.

**Comment by mattiaband** [comment]
same problem for me :(

**Comment by mutiullah7** [comment]
yeah, me too, having same issue. and now it's not even loading anymore, please help

**Comment by Hypocrite** [comment]
Problem seems to be again with the Codebird token at https://api.jublo.net/codebird/oauth2/token.

**Comment by bluelevel-media** [comment]
seems to be back up to speed again....hmmm
