### ISSUE TITLE
Twitter Loading in Slowly

### ISSUE THREAD

**Issue by emmadalby** [pavelk2/social-feed#313]
Hi there,

I am building a social feed for a client (see attached photo) and I have encountered an issue with the twitter feed loading in considerably slower than the rest of the social feeds. Pinterest, FaceBook and Instagram load in almost instantaneously, however, the Twitter feed sometimes takes almost up to 2 minutes to load in? 

Has anyone else had this issue and how do I fix it?

Thanks in advance!

![screenshot 1](https://user-images.githubusercontent.com/37620397/37707289-969fcb24-2cfa-11e8-9f16-5b00e923d28f.png)

**Comment by kierweb** [comment]
I had the same problem - you'll need to use the  Codebird-Cors-Proxy
https://github.com/jublonet/codebird-cors-proxy

And then add proxy: "/codebird-proxy/" to the twitter variables.

**Comment by emmadalby** [comment]
Thanks for the quick answer! This worked brilliantly - Thanks :)
