### ISSUE TITLE
Facebook Pages / User feed not pulled

### ISSUE THREAD

**Issue by ghost** [pavelk2/social-feed#34]
I've attempted pulling the feed from multiple pages and users.

posts?ids=meteorologistgregdee,steveadamsonkark,ChiefKeithMonahan&limit=5
feed?ids=meteorologistgregdee,steveadamsonkark,ChiefKeithMonahan&limit=5

Although those will work within the graph api explorer, it seems that either users or pages are not working.

**Comment by pavelk2** [comment]
In fact if you want to pull feeds from multiple users - you need to defined them as an array: ['meteorologistgregdee','steveadamsonkark','ChiefKeithMonahan']. Socialfeed will make 3 requests in this case.

**Comment by pavelk2** [comment]
so, can we close the issue?

On Fri, May 9, 2014 at 12:58 PM, josephmcasey notifications@github.comwrote:

> Haha, I was about to say that I had tried that, but .....Wow.... Ok I'm
> dumb.
> 
> For some reason, Ad Block Plus blocks only the facebook posts. Curious
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pavelk2/social-feed/issues/34#issuecomment-42638594
> .

## 

_Best regards,_
_PhD Student Pavel Kucherbaev_
_University of Trento, Italy_
_http://kucherbaev.com http://kucherbaev.com_

**Comment by ghost** [comment]
Yes

Joseph Casey
