### ISSUE TITLE
tag-listing items from social networks

### ISSUE THREAD

**Issue by Orange-Fox** [pavelk2/social-feed#35]
Please, add a feature to show items from social networks by hashtag. TIA

**Comment by pavelk2** [comment]
Hi,

I think that I have solved this issue with the commit https://github.com/pavelk2/social-feed/commit/1170137c836d4c1c314ef731d6317a4e6c1ec3c7. Please give it a look

**Comment by Orange-Fox** [comment]
Thank you, Pavel, I will check it as soon as my home internet connection will work.

Best regards, Orange Fox.
