### ISSUE TITLE
Try to get more than 1999 feed details from facebook

### ISSUE THREAD

**Issue by sahanDissanayake** [pavelk2/social-feed#36]
$(document).ready(function(){
        $('.social-feed-container').socialfeed({
                    //FACEBOOK--------------------
                    facebook:{
                        accounts:['simplepickup'], //usernames or id
                        limit:8888,
                        token:'240696342763428|FgHgjfn7wWMNT15ONHP0tVdWm_k' //you can also create an app and put  here your 'APP ID|APP SECRET' - it is easier but not safe
                    },
                    //GENERAL SETTINGS--------------
                    length:130,
                    show_media:true,
                    callback: function(){
                        console.log('all posts are collected');
                    }
                });
});

So with this code the plugin must have pulled more than 1 year of feed. But it pulls only upto 3 moths or 300 feed items. 

Any reason why ?

Many thanks

**Comment by pavelk2** [comment]
I think that the reason for it is the pagination of facebook feed. I will
try to give a look as soon as I have some time.

On Thu, Jun 12, 2014 at 11:21 AM, sahanDissanayake <notifications@github.com

> wrote:
> 
> $(document).ready(function(){
> $('.social-feed-container').socialfeed({
> //FACEBOOK--------------------
> facebook:{
> accounts:['simplepickup'], //usernames or id
> limit:8888,
> token:'240696342763428|FgHgjfn7wWMNT15ONHP0tVdWm_k' //you can also create
> an app and put here your 'APP ID|APP SECRET' - it is easier but not safe
> },
> //GENERAL SETTINGS--------------
> length:130,
> show_media:true,
> callback: function(){
> console.log('all posts are collected');
> }
> });
> });
> 
> So with this code the plugin must have pulled more than 1 year of feed.
> But it pulls only upto 3 moths or 300 feed items.
> 
> Any reason why ?
> 
> Many thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pavelk2/social-feed/issues/36.

## 

_Best regards,_
_PhD Candidate Pavel Kucherbaev_
_University of Trento, Italy_
_http://kucherbaev.com http://kucherbaev.com_

**Comment by sahanDissanayake** [comment]
Thanks Pavel. Looking forward.

**Comment by sahanDissanayake** [comment]
Also Mate,

https://developers.facebook.com/tools/explorer?method=GET&path=112251042194128%2Fposts%3Flimit%3D25&version=v2.0

Just had a look at the Facebook graph api and found out that there is only 25 that is recommended and also there is a next and previous links on the JSON object if we need to load more data.

So there is hope here to add a button in the plugin and load more data to the view.

**Comment by pavelk2** [comment]
There is another issue - about making "show more" functionality and "check for updates". I am quite busy right now - but later on will try to improve the the plugin with these features.

**Comment by sahanDissanayake** [comment]
Not a problem. I will be using this plugin and I will fix it make a pull request. So then you could have a look later on

**Comment by pavelk2** [comment]
great - appreciate very much external contributions!

On Thu, Jun 12, 2014 at 2:45 PM, sahanDissanayake notifications@github.com
wrote:

> Not a problem. I will be using this plugin and I will fix it make a pull
> request. So then you could have a look later on
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pavelk2/social-feed/issues/36#issuecomment-45886437.

## 

_Best regards,_
_PhD Candidate Pavel Kucherbaev_
_University of Trento, Italy_
_http://kucherbaev.com http://kucherbaev.com_
