### ISSUE TITLE
Fluid grid template

### ISSUE THREAD

**Issue by Orange-Fox** [pavelk2/social-feed#39]
I suggest you to write a fluid grid template for the feed. How'd you like it? It may look like http://wall.cosmic-gate.de 

I think it's awesome and you could add this template to your project. 

Thank you!

**Comment by pavelk2** [comment]
The idea of social-feed is to be flexible and to provide the minimum added value. What you are describing here - is to create one more template. I would keep this part on the side of a developer who uses the plugin.
