### ISSUE TITLE
code license?

### ISSUE THREAD

**Issue by jdaguil** [pavelk2/social-feed#42]
@pavelk2 what is the license for the code?

**Comment by pavelk2** [comment]
Dear @jdaguil, I did not go yet into details of different licensees. 
I think that the MIT license is the appropriate one.

Free for personal, academic and commercial use,
Users are free to do modifications. Users are encourages to contribute with improvements but are not forced to do so.

**Comment by pavelk2** [comment]
Fixed with the commit https://github.com/pavelk2/social-feed/commit/03cb66c8b856ae85ff3772f5c4c06c9fdc341551

**Comment by jdaguil** [comment]
thanks @pavelk2!
