### ISSUE TITLE
Content from users on my Facebook page displayed?

### ISSUE THREAD

**Issue by ghost** [pavelk2/social-feed#46]

**Comment by pavelk2** [comment]
Dear Simo389,
You can define a moderation function:
moderation: function(content){
                    var ban_list = ["john1", "john2", "john3"];
                    return  ban_list.indexOf(content.author_name) == -1;
                },
Please test it out - i think it should work fine.

If you want to show only posts posted by you (or limited set of trustful people) - put there usernames in a list and do instead:
var access_list = ["john1", "john2", "john3"];
                    return  ban_list.indexOf(content.author_name) != -1;

**Comment by adamlachmann** [comment]
Using moderation to block user posts is not a good solution. If we set a limit of posts to 5, and last >5 posts were made by users then our feed will be empty.

Much better solution is to change line 78:

``` javascript
request_url = fb_graph + username + '/feed?' + limit + query_extention; 
```

to

``` javascript
request_url = fb_graph + username + '/posts?' + limit + query_extention; 
```

That way Graph API will return only posts created by page admns. It would be easy to make this as a configurable option. I'm probably gonna make some contributions to this project later, since i also fixed small facebook images.

**Comment by sahanDissanayake** [comment]
@meathor How did you fix the facebook image size ?

Would you like to mention it please ?

Thanks

**Comment by manlioma** [comment]
@meathor thank you very much! 
any news for facebook image size ?? 
thanks

**Comment by sahanDissanayake** [comment]
@manlioma @pavelk2 

Here is the solution for the "small images on facebook"

https://github.com/sahanDissanayake/social-feed/commit/dcef01ea6280d8957ea5c4789f721c256ef5439d

**Comment by pavelk2** [comment]
Thank you very much @sahanDissanayake, I have merged your code

**Comment by manlioma** [comment]
Thank you guys ! you rules !!

Manlio Massimetti
+39 339 28 26 912
mmanlio@gmail.com

2014-10-02 9:56 GMT+02:00 Pavel Kucherbaev notifications@github.com:

**Comment by pavelk2** [comment]
The issue about image sizes are discussed here https://github.com/pavelk2/social-feed/issues/51
I close this issue.
