### ISSUE TITLE
Twitter: Time on Firefox

### ISSUE THREAD

**Issue by amichel86** [pavelk2/social-feed#49]
Hi, great plugin!

I found a small bug but this is maybe related to "moment.min.js" - On Firefox when displaying tweets it always says "a few seconds ago" even if the tweet has been posted 2 days ago. When viewing the same page in Chrome or IE the correct date appears. Is this a known bug?

Thanks,
Alex M.

**Comment by pavelk2** [comment]
You are right. There is also a problem in Safari.
The problem seems to be somewhere here
https://github.com/pavelk2/social-feed/blob/gh-pages/js/jquery.socialfeed.js#L219-L223

**Comment by amichel86** [comment]
Would you know a fix for this by any way? :)

**Comment by pavelk2** [comment]
I will try to fix it.

**Comment by amichel86** [comment]
That's great, thank you very much for your quick response and awesome service!

**Comment by pavelk2** [comment]
Try it out again, i think i fixed it.

https://github.com/pavelk2/social-feed/commit/7baf631011bf394210333f46de3d403b3f66ac33

**Comment by amichel86** [comment]
It's working however at line 352 there's an error for "Instagram" and it's causing the script to crash.

**Comment by pavelk2** [comment]
Could you please send me a link where the script crashes? I don't see this error in http://pavelk2.github.io/social-feed/

**Comment by amichel86** [comment]
![image](https://cloud.githubusercontent.com/assets/5871701/4529980/79168fa4-4d7c-11e4-9210-6926ae818710.png)

Here's a screenshot from the Firefox error console. I am only using Twitter in my project that's is maybe the reason why you don't see it on your side?

**Comment by pavelk2** [comment]
I see now. I will fix.

**Comment by amichel86** [comment]
Perfect, you're the man!

**Comment by pavelk2** [comment]
Please check out the updated version

**Comment by amichel86** [comment]
Looks fixed to me! Thanks
