### ISSUE TITLE
Error on facebook by hashtag

### ISSUE THREAD

**Issue by matteobresciani** [pavelk2/social-feed#50]
Hi,
I tried your script and there is an error on facebook hashtag.
The returned error is:
"error": {
      "message": "(#11) Post search has been deprecated",
      "type": "OAuthException",
      "code": 11
   }

I think your plugin use the version 1.0 of the graph api.
Can you upgrade to the newest version 2.1?

Thank you

**Comment by pavelk2** [comment]
this functionality is depreciated in 2.1, I defined explicitly v.1.0 - it works now (until facebook will completely remove its support)
https://github.com/pavelk2/social-feed/blob/gh-pages/js/jquery.socialfeed.js#L245-L248
