### ISSUE TITLE
Images for different types of Facebook post aren't formatted correctly.

### ISSUE THREAD

**Issue by ghost** [pavelk2/social-feed#51]

**Comment by pavelk2** [comment]
You are right. There is no a single format of images at facebook posts, so it is tricky to bring them to a single format. I am still in the process of finding the best way to display this variety of images. If you have an idea how to solve this issue - please let me know.

**Comment by pavelk2** [comment]
Do you mean based on the formatting of the url, or check what is the picture behind this url and apply different css?

**Comment by sahanDissanayake** [comment]
@pavelk2 

Lets have a look at this. Let me know

https://github.com/sahanDissanayake/social-feed/commit/877eeddae79da64294d407b516136eb3ae720439

**Comment by pavelk2** [comment]
@sahanDissanayake 
Hi,
I have checked your code, did my improvement based on it, please give it a look:
https://github.com/pavelk2/social-feed/commit/2915f3701e593c2dc48152938e8e0b8151a26212

Summary:
i defined several conditions for facebook picture with associated modifications,
if finally we have a very small image - which is less than media_min_width defined in options, then this image simply will not be shown.

**Comment by sahanDissanayake** [comment]
@pavelk2 Yep Looks great. Keep up the great work. :trophy:
