### ISSUE TITLE
Instagram feed not working with username

### ISSUE THREAD

**Issue by teemuinto** [pavelk2/social-feed#53]
Instagram photos won't show with username, only with hashtag. There might be a problem getting the user id from username. Works when using the numeral user id with the getImages function.

**Comment by Fwanz** [comment]
I found the function getUsers is not validating properly the account name attribute, and the variables limit, query_extention and igm_api_base are not reaching that point. The temporary solution I have found is this:

``` javascript
case '@':
    var username = account.substr(1);
    url = igm_api_base + 'users/search/?q=' + username + '&' + query_extention;
    //Utility.request(url, Feed.instagram.utility.getUsers); 
    $.ajax({
        url: url,
        dataType: 'jsonp',
        success: function (json) {
            json.data.forEach(function (user) {
                if (user.username.toLowerCase() === username.toLowerCase()) {
                    var url = igm_api_base + 'users/' + user.id + '/media/recent/?' + query_extention;
                    Utility.request(url, Feed.instagram.utility.getImages);
                }
            });
        }
    });
    break;
```

Hope it helps!

**Comment by iaian** [comment]
I had the same issue and Fwanz's solution worked for me. Thanks 
+1
