### ISSUE TITLE
Twitter feeds not always showing

### ISSUE THREAD

**Issue by samimikk** [pavelk2/social-feed#54]
Not sure if this more like codebird.js issue, but seems at the moment Twitter feeds are not retrieved in every page refresh in social feed. 

Console is not giving any error, but still Twitter feeds do not show up. It can be even reproduced on your  http://pavelk2.github.io/social-feed/ page. Sometimes it shows twitter feeds and then it wont :(

**Comment by pavelk2** [comment]
Dear @samimikk, I think that the reason for that is the limit of 150 requests per hour, which Twitter introduces, and I believe codebird stays in this limit.
How to handle it?
We can use this api: http://tweecool.com/

**Comment by samimikk** [comment]
Thanks for the clarification!

**Comment by samimikk** [comment]
Seems that api.jublo.net is not working properly at the moment, which causes really long response times for Twitter feeds.
