### ISSUE TITLE
Is There all network feed complete function

### ISSUE THREAD

**Issue by vedattaylan** [pavelk2/social-feed#56]
Thanks

**Comment by pavelk2** [comment]
the implementation of such a callback is started https://github.com/pavelk2/social-feed/blob/gh-pages/js/jquery.socialfeed.js#L30-L38
but currently does not work properly.

Please feel free to contribute and to submit your pull request.

**Comment by pavelk2** [comment]
Duplicate with https://github.com/pavelk2/social-feed/issues/32
