### ISSUE TITLE
Demo code is not finding any tweets

### ISSUE THREAD

**Issue by jyoung4** [pavelk2/social-feed#57]
I noticed the demo code and when I downloaded the code it does not seem to be finding any tweets yet there are plenty of elonmusk tweets

**Comment by pavelk2** [comment]
Dear jyoung4,
I have noticed the same issue - the service which is used in this plugin for parsing tweets via client side is not working properly. I create a server side for the Social-feed to solve this issue and also to solve the security issue we have by keeping all the credentials public in the client side. I will make an update in this repository as soon as I have some progress with this.

**Comment by jyoung4** [comment]
Yay! The code is working today!!!! I hope it stays up. Let me know if you develop a server side that we can be sure will stay up. For know I will continue with your wonderful code.

**Comment by pavelk2** [comment]
Hey jyoung4, I am glad that it works and glad that you like it.
I work on the server side here: https://github.com/pavelk2/social-feed-server, so far it is very rough and I do not recommend to use it. As soon as I do the first release version - you can try it out.
