### ISSUE TITLE
how to change the layout like instagram and load more button 

### ISSUE THREAD

**Issue by bajpangosh** [pavelk2/social-feed#58]
can u update the front page have some cool interface change the layout like Pinfinity Responsive Tumblr-Like Site Template  and a load more button in footer

**Comment by pavelk2** [comment]
Dear Bajpangosh, 
SocialFeed is an open-source jQuery plugin which aims to provide generic features. Custom features, such as "cool interface layout like Pinfinity Responsive Tumblr" can be done by a developer using the plugin adjusting the template file (template.html) the CSS files. Regarding the load more button: this feature was requested before and I hope to get to it at some point. If you feel that you can help here - I appreciate a lot contributions from other developers. Thank you.

**Comment by pavelk2** [comment]
Dear Bajpangosh,
One more thing. It does not work like this: http://entevaka.ml/. You can not just copy the whole work, keeping my secret credentials and posting it on your website, claiming that all rights are on your side, without keeping any link on this repository, the original plugin webpage or my personal website. Please respect the work of others.

**Comment by bajpangosh** [comment]
Don't worry my brother i fixed. that site for just testing and i want to add more Modifications on that plugin after completed i won't forgot you my friend i will put all credits goes to Pavel Kucherbaev and one more thing put a footer on that plugin
