### ISSUE TITLE
Moderation: more than one word in filter/

### ISSUE THREAD

**Issue by andyUA** [pavelk2/social-feed#59]
How to add more than one word in moderation filter?

**Comment by pavelk2** [comment]
moderation - is a regular javascript function, which if returns true - the post is visible, if returns false the post is hidden.
So you can design this function in whatever fashion you feel comfortable. You might consider using arrays.

``` javascript
moderation: function(content) {
    allow = true;
    if (content.text) {
        var keywords = ["bad word1", "bad word2", "bad word3"];
        for (var i = 0; i < keywords.length && allow; i++) {
            if (content.text.indexOf(keywords[i]) != -1) {
                allow = false;
            }
        }
    }
    return allow;
}
```
