### ISSUE TITLE
Twitter time display in IE

### ISSUE THREAD

**Issue by mlkowalczyk** [pavelk2/social-feed#61]
IE shows "a few seconds ago" for all time displays for Twitter. Do you have an idea of what could be causing that?

**Comment by aspoche** [comment]
Yes, I saw the same issue : Internet Explorer 11 (or below) 
display "a few seconds ago" in the news - Please can you take a look quickly ? Thank you

**Comment by whSarah** [comment]
Same issue here in IE 11. dt-create has the value "nan".
I fixed it by changing line 270 
from:
`post.dt_create = moment(new Date(element.created_at));`
to:
`post.dt_create = moment(element.created_at, 'dd MMM DD HH:mm:ss ZZ YYYY','en');`

If you need a differnt locale you can change it afterwards like this:
`post.dt_create.locale('de');`
