### ISSUE TITLE
Utilityrequest(request_url, Feed.google.utility.getPosts);

### ISSUE THREAD

**Issue by tiptronic** [pavelk2/social-feed#62]
Bower pulls a different version/setup than which is on GIT

It also contains some errors:
e.g. line 307:  
Utilityrequest(request_url, Feed.google.utility.getPosts);

should be:
Utility.request(request_url, Feed.google.utility.getPosts);

**Comment by pavelk2** [comment]
Thank you for pointing this. With a new stable version (in 7-10 days) i will create a new release and update bower.
