### ISSUE TITLE
Secure HTTPS?

### ISSUE THREAD

**Issue by cocomo** [pavelk2/social-feed#64]
Awesome software, thank You for sharing it! I think I ran into an issue switching to secured HTTPS connections. Now I'm reading through codebirds documentation and it feels strange. Has anyone else used HTTPS?

**Comment by abkhan25** [comment]
some of the instagram images are comming from non https: links

**Comment by cocomo** [comment]
Until Instagram fixes their api response this replacement in Feed.instagram.utility.unifyPostData() might help:

```
if (element.images.standard_resolution.url.indexOf("http://") != -1) { 
    post.attachment = 
        '<img class="attachment" src="https://' + element.images.standard_resolution.url.substring(7) + '' + '" />'; 
}
```
