### ISSUE TITLE
Twitter feeds

### ISSUE THREAD

**Issue by abkhan25** [pavelk2/social-feed#65]
twitter handles and # are not showing up

**Comment by loveblank** [comment]
The problem seems to be the codebird CORS proxy that is not responding: https://api.jublo.net/codebird/oauth2/token

**Comment by Grabes** [comment]
How can we setup another CORS proxy to get around this issue?

**Comment by sahanDissanayake** [comment]
@pavelk2 get this error most of the time

 GET https://api.jublo.net/codebird/1.1/statuses/user_timeline.json?id=mcuban&count=30 429 (Too Many Requests)

Even after making a quick 2 or 3 requests

**Comment by pavelk2** [comment]
Are you sure that you use your own twitter credentials? If you use the once used in the social-feed project page - then it is reasonable.

**Comment by Grabes** [comment]
Sahan's issue is with his twitter credentials.

The original issue was with the api.jublo.net site going down completely (502 error). It was only for about one hour and then it came back up. Everything seems to be working now and the issue was not with this plugin.

**Comment by pavelk2** [comment]
Thank you for the clarification.
