### ISSUE TITLE
Select only items with image

### ISSUE THREAD

**Issue by pilarmera** [pavelk2/social-feed#67]
Hi! 
I need to grab only the social items with an image attached. I managed to at least not displaying them changing the template like that: 

```
               {{? !it.attachment}}<span></span>{{?}}
                {{? it.attachment}}                    
            <article class="social-feed-element {{=it.social_network}}" dt-create="{{=it.dt_create}}" social-feed-id = "{{=it.id}}">
                <p class="social-feed-info"><small><span><a href="{{=it.author_link}}" target="_blank" class="tips icon" title="{{=it.author_name}}" ><img src="{{=it.author_picture}}" alt="" class="img-responsive circle"></a></span><span class="pull-right">{{=it.time_ago}}  <i class="fa fa-{{=it.social_network}}"></i></span></small>                        
                </p>
                <figure>
                    <a href="{{=it.link}}" class="hover-effect" target="_blank">{{=it.attachment}}</a>
                    <figcaption class="no-mt">
                            <p class="social-feed-text small">
                                {{=it.text}}
                            </p>
                        </div>
                    </figcaption>
                </figure>
            </article>{{?}}
```

After that I can style the displayed items them with nth-of-type, for example.

But with this method I can't control how many Twitter or Facebook items are displayed (I don't have this problem with Instagram, as all its items have image): I need to set a very high 'limit' in Twitter to make sure the feed will grab at least some tweets with an image attached, and even then I can't know exactly how many will they be.

Thank you very much in advance, and thank you already for your work
Pilar

**Comment by pavelk2** [comment]
Dear @decrecementofeliz,

Unfortunately we don't have currently a solution to your problem. We are working now on a server-side for Social-feed. This could help. But no solutions to that so far. Please update me if you found a workaround.
