### ISSUE TITLE
Callback Function

### ISSUE THREAD

**Issue by Grabes** [pavelk2/social-feed#69]
I am wondering how to implement the callback function as it looks like it was commented out. 

Any suggestions for how it could be implemented?

**Comment by pavelk2** [comment]
There might be better ways to implement such a function, but the solution I see:
we define a variable 
var requests_left = 0;
every time before to send a request we do requests_left++;
every time we receive a response for a request we do requests_left-- and check if requests_left == 0, then we call a callback function.

This implementation is not elegant enough, but just came from the top of my head.

**Comment by jbasoo** [comment]
Would be great if this could be fixed. I need to remove the moderated items from the DOM, not just add .hidden, was hoping to be able to do it in the callback.

**Comment by gian-reto** [comment]
Based on the suggestion of @pavelk2 I added two new variables: posts_to_load_count (calculated from your limit numbers and number of accounts) and  loaded_post_count. loaded_post_count increments every time when a post is rendered. If it matches with posts_to_load_count, the callback gets called. Pretty simple.

Still waiting for the pull request to get accepted though: #80

**Comment by pavelk2** [comment]
Duplicate https://github.com/pavelk2/social-feed/issues/32
