### ISSUE TITLE
sorry not really an issue!

### ISSUE THREAD

**Issue by kevblucasuni** [pavelk2/social-feed#70]
hi i am trying to use this and have connected to facebook twitter and instagram. my issue is that the search is now not working. plus i would like to add sound cloud have u any idea which parts i would need to amend.
thanks

**Comment by pavelk2** [comment]
So for the sound cloud - you need to go into jquery.socialfeed.js - see how some other social networks are implemented (e.g. look for instagram) and add the code according to the example for the sound cloud API.

Regarding the issue you have - what does mean - "search is not working" - which search? Please try to provide more info so I or any other contributor on github here could help you to fix it.

**Comment by kevblucasuni** [comment]
brilliant thank you. the search problem im having happens when i link my account to it the search no longer brings up any search results and just brings up my feeds.

**Comment by pavelk2** [comment]
@kevblucasuni do you still have the problem? To be honest I could not get the point.
