### ISSUE TITLE
Question: setting limit - higher value, less posts

### ISSUE THREAD

**Issue by karlienfabre** [pavelk2/social-feed#71]
Hi! 

First of all, nice plugin. The only little issue is that all your tokens are just in de JS so everyone can see them; or is there a solution for that?

The real question: I don't really understand the setting 'limit' of social media channels. I'm using 3 channels (facebook, twitter and instagram) and I've set the limit of all 3 on 200. Then I get 336 post in total (I count the html elements). But, if I set an higher value for the limit (ex. 500) I only get 226 post back... What's the system? It also seems some post are not showing up (ex. instagram post from link)

Can you explain why it is like that? Or what I'm doing wrong? 

Thx!

http://staging.karlienfabre.be/bas/timeline.php
https://instagram.com/p/smeuwBmYCW

**Comment by pavelk2** [comment]
Dear Karlienfabre,

I think the reason for such an error is that the social-feed is not
designed for the big feeds. Social-feed gets data from social-networks in
paginated JSONS. Social-feed does not parse the pages, but shows only the
posts from the first page.

Why there are 226 posts if you request more - to be honest, I don't know. I
suggest you to localize the problem and to check which social-network
exactly gives less posts (i guess it is Facebook). If it is Facebook - i
don't know the reason why does it work like this, the logic of how the open
graph api retrieves posts is not defined well anywhere.

Please feel free to investigate the issue and possibly contribute with your
solution. I am very happy to accept your pull-request.
