### ISSUE TITLE
Google plus page feed

### ISSUE THREAD

**Issue by dbertella** [pavelk2/social-feed#72]
I noticed that if I put a page name I got an error because the plugin is requesting a people url, do you think that is possible to switch to a page url?

Thank you very much

**Comment by pavelk2** [comment]
Technically yes. I think that for  this purpose we need to send a request to another API endpoint of Google+ to get back the ID, and then do what the social-feed does now. If you would implement this feature - I am very happy to accept your pull request.

**Comment by dbertella** [comment]
Cool, I'll look into it, I was already looking actually but I need to dig
more into google+ api, I'll let you know

2015-03-31 10:49 GMT+02:00 Pavel Kucherbaev notifications@github.com:

> Technically yes. I think that for this purpose we need to send a request
> to another API endpoint of Google+ to get back the ID, and then do what the
> social-feed does now. If you would implement this feature - I am very happy
> to accept your pull request.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pavelk2/social-feed/issues/72#issuecomment-87998352.

## 

Daniele Bertella
*web designer & developer *

+39.340.490.57.80
info@danielebertella.com
LinkedIn: danielebertella http://it.linkedin.com/in/danielebertella/
Twitter: _denb https://twitter.com/_denb
www.danielebertella.com

**Comment by pavelk2** [comment]
Great!

**Comment by dbertella** [comment]
I found that probably you will need to use a google client library and I
found the js one with the other backend languages
https://developers.google.com/api-client-library/javascript/start/start-js

but I don't think is what we need, because the user needs to authorize the
app to see the streaming, and by the way I still can't get it working..

2015-03-31 10:54 GMT+02:00 Pavel Kucherbaev notifications@github.com:

> Great!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pavelk2/social-feed/issues/72#issuecomment-88000696.

## 

Daniele Bertella
*web designer & developer *

+39.340.490.57.80
info@danielebertella.com
LinkedIn: danielebertella http://it.linkedin.com/in/danielebertella/
Twitter: _denb https://twitter.com/_denb
www.danielebertella.com

**Comment by dbertella** [comment]
Actually I think you were right.

You just need to have the id instead of the name and you will get the post
from the google plus page.

I'll check if there is an automate way to get it, but the problem is that
if the name on facebook is different from the username in google plus, it
throw an error anyway because it doesn't find nothing at the link provide.

Still digging around

2015-03-31 12:10 GMT+02:00 daniele bertella daniele.bertella@gmail.com:

> I found that probably you will need to use a google client library and I
> found the js one with the other backend languages
> https://developers.google.com/api-client-library/javascript/start/start-js
> 
> but I don't think is what we need, because the user needs to authorize the
> app to see the streaming, and by the way I still can't get it working..
> 
> 2015-03-31 10:54 GMT+02:00 Pavel Kucherbaev notifications@github.com:
> 
> > Great!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/pavelk2/social-feed/issues/72#issuecomment-88000696.
> 
> ## 
> 
> Daniele Bertella
> *web designer & developer *
> 
> +39.340.490.57.80
> info@danielebertella.com
> LinkedIn: danielebertella http://it.linkedin.com/in/danielebertella/
> Twitter: _denb https://twitter.com/_denb
> www.danielebertella.com

## 

Daniele Bertella
*web designer & developer *

+39.340.490.57.80
info@danielebertella.com
LinkedIn: danielebertella http://it.linkedin.com/in/danielebertella/
Twitter: _denb https://twitter.com/_denb
www.danielebertella.com

**Comment by pavelk2** [comment]
In fact the thing that the name on facebook and google plus do not match is completely fine. You suppose to define the account names for different social networks separately as it is described in the readme file.

**Comment by dbertella** [comment]
You are right man, sorry I was just looking at the example :-)

2015-03-31 22:49 GMT+02:00 Pavel Kucherbaev notifications@github.com:

> In fact the thing that the name on facebook and google plus do not match
> is completely fine. You suppose to define the account names for different
> social networks separately as it is described in the readme file.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pavelk2/social-feed/issues/72#issuecomment-88239818.

## 

Daniele Bertella
*web designer & developer *

+39.340.490.57.80
info@danielebertella.com
LinkedIn: danielebertella http://it.linkedin.com/in/danielebertella/
Twitter: _denb https://twitter.com/_denb
www.danielebertella.com
