### ISSUE TITLE
Fix for media_min_width Bug!

### ISSUE THREAD

**Issue by der-lukas** [pavelk2/social-feed#75]
Hey! Thanks for this great social-feed!

The media_min_width didn't work for me in your code, because when you checked if the width is bigger than the minimum width, the image was already resized by CSS.

I fixed this by creating a new image, applying the "old" image-src to this, taking it's dimensions and deleting it again...

```
// preload the image
var height, width = '';
var img = new Image();
var imgSrc = image.attr("src");

$(img).load(function () {
if (img.width < options.media_min_width) {
        image.hide();
    }
    // garbage collect img
    delete img;
}).error(function () {
img.hide();
// image couldnt be loaded
console.log('An error occurred and your image could not be loaded.  Please try again.');
}).attr({ src: imgSrc });
```

Found this code snippet here (which was the first one to work after trying a lot of methods before)
http://stackoverflow.com/a/1833000/3754201

**Comment by pavelk2** [comment]
Great. Could you create a pull-request, so I accept it to the main branch?
