### ISSUE TITLE
Facebook array problem

### ISSUE THREAD

**Issue by mskayali** [pavelk2/social-feed#78]
I create an app in facebook than I get app-id and app-secret but only facebook array doesn't work.

<pre>
           $('.social-feed-container').socialfeed({
                        // FACEBOOK
                        facebook:{
                            accounts: ['@username','#username'],
                            limit: 10,
                            access_token: '143775004980049|b437aa4b0c0c0c06a8f6c0c0cc80e6299' // APP_ID|APP_SECRET
                        },
                        // BLOGSPOT
                        /*blogspot:{
                            accounts:['@iman-khaghanifar']
                        },*/
                        // GENERAL SETTINGS
                        length:400,
                        show_media:true,
                        // Moderation function - if returns false, template will have class hidden
                        moderation: function(content){
                            return  (content.text) ? content.text.indexOf('fuck') == -1 : true;
                        },
                        //update_period: 5000,
                        // When all the posts are collected and displayed - this function is evoked
                        callback: function(){
                            console.log('all posts are collected');
                        }
                    });
</pre>

**Comment by pavelk2** [comment]
do you leave accounts as "@username" and "#username"? Or do you put there something? Try to put there "@barack.obama" and see if you receive any posts.

**Comment by mskayali** [comment]
Absulitly not. I use my own account name and my   app id and secret code. also github demo codes doesnt get the facebook array in my browser. But other social media array comes.

**Comment by mskayali** [comment]
There is no console bug in chrome..

**Comment by pavelk2** [comment]
I really want to help, but i don't understand the problem.
1) does it work for you when you use the facebook access_token to show posts from the account "@barackobama"?
2) does it work for you when you use your own facebook access_token to show posts from the account "@barackobama"?
3) does it work for you when you use your own facebook access_token to show posts from your account?
4) does it work for you when you use the facebook access_token to show posts from your account?

**Comment by pavelk2** [comment]
As there were no further requests - I close this issue.
