### ISSUE TITLE
Do not working in medium trust IIS7

### ISSUE THREAD

**Issue by AliAtes** [pavelk2/social-feed#81]
I'm using jquery social-feed plugin in my asp.net mvc 5 app on IIS7 full trust. There are not any problem but when I upload the plugin share server that is medium trust IIS7 it is not working and I don't understand what is the problem?

Refer: http://stackoverflow.com/questions/29697995/jquery-social-feed-plugin-not-working-medium-trust-iis7

**Comment by AliAtes** [comment]
My administrator telling that "Session times are restricted" what did he mean?

**Comment by pavelk2** [comment]
I believe that the question should be addressed to IIS7 community rather than this plugin specifically. I close this issue - please let me know if you still have this problem.
