### ISSUE TITLE
Facebook Hashtag 

### ISSUE THREAD

**Issue by chrisedington** [pavelk2/social-feed#88]
Hi,

Having an issue with Facebook hashtags being pulled into the feed. Seems like @names work, but not Hashtags.  Seems like its the same case on the demo when using #elonmusk.

Some info:
1. If I use this I get posts from the @name value:
   
   facebook:{      accounts: ['@teslamotors','#teslamotors'],
2. If I use this, I don't get anything at all.

facebook: {        accounts: ['#finishgreat','#teslamotors'],
1. If I use this, I don't get anything at all.

facebook: {          accounts: ['#finishgreat'],

Any idea how I can solve this?

**Comment by yp28** [comment]
Little late, but if I'm not mistaken, the Facebook API does not support posts based on hashtag anymore ([source](http://thenextweb.com/facebook/2015/04/03/facebook-might-be-shutting-down-access-to-hashtags-in-its-api/)).

**Comment by Webarkitekt** [comment]
I confirm and it's no more available in social-feed doc.
