### ISSUE TITLE
video feeds not getting

### ISSUE THREAD

**Issue by ghost** [pavelk2/social-feed#89]
Hi , Is there any option to get video posts also?

**Comment by Webarkitekt** [comment]
@mujeebu You mean video attached with the post ?

**Comment by ghost** [comment]
Yes. Video feeds are not rendeing

**Comment by pavelk2** [comment]
@mujeebu,
Currently the attachments are formed as images only. This is so far - by design. Would you like to create a pull request where you check whether the content inside is a video and make it playable?
