### ISSUE TITLE
facebook post not showing

### ISSUE THREAD

**Issue by DhruvaRajan** [pavelk2/social-feed#90]
1st of all I want to thank you for this awesome library, I downloaded the latest version but for some reasons the face post are not seen, even in your demo link one cannot see facebook post, please check the Facebook part for some reasons the Facebook post are not displayed.

and thank you for the library :)

**Comment by DhruvaRajan** [comment]
@pavelk2 plz took into this, need your help

**Comment by pavelk2** [comment]
The facebook API is changed, so currently some functionality is not available. Please check the latest update in SocialFeed about it: https://github.com/pavelk2/social-feed/pull/87
