### ISSUE TITLE
Google+ post length issue

### ISSUE THREAD

**Issue by njtam** [pavelk2/social-feed#92]
Hi Pavel,

Thanks for developing this awesome plugin!  I have a question.  I'm using the plugin mainly to display Google+ posts and ran into the issue where posts longer than about 100 characters would not display. Other social networks are fine.  Just Google+ has this issue.  I tried changing the length value under General Settings and in jquery.socialfeed.js, but no luck there.  

Please let me know if there is a way of fix this or maybe there's something I overlooked? 

Thanks so much,
NJ

**Comment by pavelk2** [comment]
Hi @njtam,

Thank you very much for pointing this out.

From my tests - I still receive the posts which have length longer than 100 characters, but they are still shortened to 100. I checked the socialfeed.js code to make sure the shortening function works in a similar way for different social networks. It does work in the same way. I found that the data from Google+ comes already shortened: 
https://www.dropbox.com/s/gftpdrzw5gmn4fq/Screenshot%202015-05-27%2010.18.36.png?dl=0

I checked the Google+ API docs:
https://developers.google.com/+/api/latest/activities/search
It is written there:

> The title of this collection of activities, which is a truncated portion of the content.

Keeping this in mind I believe that Google+ API retrieves the titles already shortened to 100 characters.

**Comment by njtam** [comment]
Hi Pavel,

Thanks for your quick and helpful response! 

Is there a way to display the actual content (full text) of the Google+ post instead of the search result title?  That way I won't have to be limited to a 100 characters and can then control the length of the text.  

Please let me know.  Thank you!

**Comment by pavelk2** [comment]
Dear Njtam,

Unfortunately so far I am not aware of such a solution. Please google it
specifically and checkout what people from stackoverflow-similar websites
say about this issue.

**Comment by njtam** [comment]
Thanks for your help Pavel!  I'll keep searching.
