### ISSUE TITLE
Google Plus - Account settings

### ISSUE THREAD

**Issue by njtam** [pavelk2/social-feed#98]
Hi Pavel,

I was wondering if there is a way where I can define in the accounts settings to only display posts with a #hashtag from specific user accounts? 

For example, only pull posts with #greatday from @+johnsmith 

Right now, if I define @userpage and #hashtag, it will pull everything from that user's page and all posts from any user with that hashtag.  

Please let me know your thoughts.  Thanks in advance! :)

NJ

**Comment by pavelk2** [comment]
Hi @njtam,
I believe that you can select posts from a given account and then use the moderation function to display only those containing a given hashtag.

**Comment by njtam** [comment]
Thanks Pavel!  I'll check it out.
